version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./certificates:/srv/certs
    ports:
      - "4000"

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        API_URL: /
    ports:
      - "3000"

  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "443:443"
