name: Deno backend code quality check

on:
  push:
    paths:
      - "backend-deno/**"

jobs:
  test:
    name: Test with ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend-deno
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      CI: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.29.1"
      - name: Format check
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Type check
        run: deno cache --import-map import_map.json **/*.{js,ts}
