name: Code quality check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: cd frontend
      - name: Install dependencies
        run: |
          pnpm install
        env:
          CI: true
      - name: Check code style
        run: pnpm run lint
        env:
          CI: true
      - name: Check build
        run: |
          pnpm run build
        env:
          CI: true
